### ISSUE TITLE
Doesn't seem to function on Linux 

### ISSUE THREAD

**Issue by ShawnMcCool** [mikecrittenden/chrome-shortkeys#12]
Chrome Version 35.0.1916.153

I can't get anything to work.

**Comment by mikecrittenden** [comment]
This isn't a general issue with Linux since I use Linux myself. Most of the time when people say "nothing works" it's just because they need to reload their tabs a few times before the shortcuts are inserted, or possibly restart the browser.

**Comment by ShawnMcCool** [comment]
Since I posted this, I figured it out. It works unless you're in a form field or in Asana or something.

**Comment by jcrben** [comment]
If anyone else runs into this, for some reason I had to reboot my computer for it to start firing. NixOS 18.03.
