### ISSUE TITLE
Turning sync on clears all data already synced

### ISSUE THREAD

**Issue by sharat87** [mikecrittenden/chrome-shortkeys#18]
I used this extension on an older computed and had quite a few shortcuts configured, with sync turned on. That computer broke and I no longer have access to it. On my new computed, after this extension is installed, I noticed that my shortcuts were not available. I went to options, but no shortcuts were configured there.

I realized that the extension is looking for shortcuts in `chrome.storage.local` and I need to turn on sync so it will look in `chrome.storage.sync`. So in the options page, I opened the developer tools' console and did a `chrome.storage.sync.get(null, function (d) {console.log(d)})` and I could see all my shortcuts just as I configured them on my old system.

So now, I go an turn on sync. No shortcuts turn up. I check `chrome.sync` again, and its empty. I lost all my shortcuts.

Now, I have to ask, why is sync optional? And can we please address this issue before it bites someone else? I'll see if I can find some time to dig in the source. If you ask me, the fix is to always use `chrome.storage.sync`.

Thank you.

**Comment by mikecrittenden** [comment]
Thanks @sharat87 - I'm in the middle of a big overhaul and this is fixed in the new version.
