### ISSUE TITLE
Add the "Find" action

### ISSUE THREAD

**Issue by zmwangx** [mikecrittenden/chrome-shortkeys#19]
It would be nice to have a custom shortcut for `Find...` (i.e., invoking Chrome's native Find dialog) because for obvious reasons some of us prefer `/` for Find.

At the moment there seems to be no way to invoke the native Find dialog through Chrome's JavaScript API (did I miss anything?). Anyway, I'm opening this issue in the hope that this feature gets implemented in the API in the future, and then we can add the action to chrome-shortkeys. The chances look very slim, though.

**Comment by mikecrittenden** [comment]
Yeah, this is something I've been wanting for a long time too. :(

Glad to leave this issue open in hopes, and maybe to increase visibility a
little bit.

**Comment by mikecrittenden** [comment]
Doesn't look like there's any hope for Chrome implementing this.

For future reference, we can check in on this SO answer from time to time to see if anyone posts with a change: http://stackoverflow.com/questions/13714127/chrome-extension-how-can-i-show-the-find-bar-and-supply-text-for-it
