### ISSUE TITLE
non-functioning under mac

### ISSUE THREAD

**Issue by gimpbully** [mikecrittenden/chrome-shortkeys#2]
I've set up a very simple rule set:
⌘+shift+right   Next Tab    All Sites
⌘+shift+left     Prev Tab    All Sites

It's completely non-functional.  Attempts at other combos similarly do not work.

Chrome Version 24.0.1312.57 on OSX 10.8.2

**Comment by mikecrittenden** [comment]
Doesn't seem to be a general issue with Macs, since I'm using a Mac myself nowadays.
