### ISSUE TITLE
Allow global shortcut keys to call chrome shortkeys for specific pages

### ISSUE THREAD

**Issue by bradparks** [mikecrittenden/chrome-shortkeys#23]
I'm wondering if you could use this to allow global shortcut keys to be defined for controlling audio playback on almost any site?

For example, I use the "Streamus" extension to listen to YouTube playlists, and it allows me to globally toggle playback and jump to prev/next tracks, which is great.

But if your extension allowed me to bind global shortcut keys to any page when it was loaded, then I could map global shortcuts to per site keyboard shortcuts for other music sites, like thesixtyone.com, and then I could toggle playback, skip tracks, etc, regardless of the music site I was currently using.

Streamus shortcuts are configured using the global chrome shortcuts, found here:

chrome://extensions/configureCommands

**Comment by mikecrittenden** [comment]
Sounds like what you want would be better suited for something like http://www.streamkeys.com/ which is built to solve that exact use cases and supports tons of music sites. I'm going to close this as out of scope, since there are already better tools for that.
