### ISSUE TITLE
How to declare numlock numbers ?

### ISSUE THREAD

**Issue by frknrhn** [mikecrittenden/chrome-shortkeys#25]
For instance ctrl+num3 doesnt seem to work. 

Any help is appreciated. 

Thanks for everything btw.

**Comment by mikecrittenden** [comment]
I'm not sure what this means exactly. Is "num3" different than the regular "3" key? Do you mean as in the keys on the right side of a full keyboard, on the number keyboard?

**Comment by frknrhn** [comment]
Yes, that was what I meant.

**Comment by mikecrittenden** [comment]
Gotcha. Yeah, unfortunately that's not supported. I believe using a number
like "3" will work with both the regular number keys and the numlock keys
as well, but I have no way of testing that.

I'll look into adding support if I have any more requests for this.

**Comment by frknrhn** [comment]
Thanks for quick reply.
