### ISSUE TITLE
Remove `console.log` at runtime

### ISSUE THREAD

**Issue by cvkef** [mikecrittenden/chrome-shortkeys#27]
Hi @mikecrittenden,

There is no reason to [`console.log(keySettings);`](https://github.com/mikecrittenden/chrome-shortkeys/blob/7d0b39363aac9413bf4c3491a9986d867ff4ed90/app/scripts/contentscript.js#L206). Please remove it.

**Comment by mikecrittenden** [comment]
Fixed - will push a release now. Good catch, sorry about that!
