### ISSUE TITLE
Not working in Opera 31 any more?

### ISSUE THREAD

**Issue by webaschtl** [mikecrittenden/chrome-shortkeys#30]
Hello,

I am using the latest version of of chrome-shortkeys in Opera 31 for Windows.

Before the update from v30 to v31I was able to edit the "keys". But now the form for the shortcuts is missing: http://abload.de/img/2015-08-14shot007d5kjk.jpg

However the defined shortcuts/shortkeys before v31 still work.

Any help?

thanks! webaschtl

**Comment by mikecrittenden** [comment]
I actually didn't create or maintain the Opera extension, so not much I can
do for this. Someone else ported the Chrome extension to Opera.

**Comment by webaschtl** [comment]
Thanks & sorry ;)

**Comment by webaschtl** [comment]
Ah, sorry, I discovered the correct addon/website: https://github.com/andreasbovens/opera-shortkeys/ -- my mistake!
