### ISSUE TITLE
Add an "open incognito tab" action 

### ISSUE THREAD

**Issue by m4ci3k2** [mikecrittenden/chrome-shortkeys#31]
Would it be possible to add an action to open incognito tab? It would be useful in my effort to have Firefox-like shortcuts.

**Comment by mikecrittenden** [comment]
Looks like this is certainly possible: https://developer.chrome.com/extensions/windows#method-create

**Comment by Elronnd** [comment]
I found the same answer in a different place, [here](https://stackoverflow.com/questions/2228118/how-to-open-new-incognito-window-with-javascript-google-chrome).  *We need this.*  Please implement it, it seems trivial.

**Comment by samcorbin** [comment]
Implemented in firefox version https://github.com/pmalecka/chrome-shortkeys/blob/master/app/scripts/options.js

**Comment by mikecrittenden** [comment]
Fixed FINALLY. Thanks for the link @samcorbin!
