### ISSUE TITLE
Add "Open website from clipboard" actions

### ISSUE THREAD

**Issue by mikecrittenden** [mikecrittenden/chrome-shortkeys#32]
An option to open in the current tab or open in a new tab would probably be nice.

**Comment by risk00** [comment]
Or if a bookmarklet exists or can be created to do this, that can be called from the extension

**Comment by mikecrittenden** [comment]
I'm going to close this since this doesn't seem to be a very common need and it'd require adding a new permission (`clipboardRead`).

For anyone who comes along and sees this, there's always `ctrl+l` then `ctrl+v` then `enter`. Feel free to reopen if you think this is more valuable than I do.

**Comment by alon91** [comment]
I'd love for you to reconsider this! Both these actions are available in [Vimium](https://github.com/philc/vimium) and I find them quite helpful on occasion. Understand that adding a permission has its own challenges, but would love to see this worked on.

(I don't believe I have permissions to reopen bugs)

![image](https://user-images.githubusercontent.com/35006176/61090370-3a2e3d00-a3f3-11e9-9e1b-665809e21114.png)
