### ISSUE TITLE
Add "Paste clipboard" action

### ISSUE THREAD

**Issue by ctsstc** [mikecrittenden/chrome-shortkeys#33]
I do not think this is possible due to JS security, but I would love to see it if it is possible
I would love to have "v v" be my paste - my hand gets fatigued through the day doing tons of ctrl-v

**Comment by mikecrittenden** [comment]
After thinking more about it, I think this is a problem that Shortkeys shouldn't solve. Copying and pasting text are OS-level operations (not browser level) and should probably be solved by OS-level tools. Try https://autohotkey.com/ for Windows or http://www.keyboardmaestro.com/main/ for Mac, for things like this that aren't really browser specific.

**Comment by mikecrittenden** [comment]
Also, it looks like https://chrome.google.com/webstore/detail/auto-text-expander-for-go/iibninhmiggehlcdolcilmhacighjamp?hl=en may work for this since it mentions clipboard paste in the description.

**Comment by hirokihokari** [comment]
@mikecrittenden 
>  Copying and pasting text are OS-level operations (not browser level)

I'm confused. You're saying that, and OS forums(superuser etc) people are saying that they won't do it since it's all application's responsibility.
