### ISSUE TITLE
having an issue + have a suggestion or two if I can..

### ISSUE THREAD

**Issue by David050203** [mikecrittenden/chrome-shortkeys#34]
Hey Mike
Im having one issue, I use this extension for tribal wars of course:) and I have one key setup to input a script then another key to click button and switch to next page..

my issue here is once i click the key that does the script I can no longer use the key that clicks the button or the key that switches tabs..

any way to fix this and also I would be forever in your debt if I could get you to add a couple more things that us tribal wars guys can use..?

If you have time to spare for me I would love to get with you on skype and if a couple things could be added, you would get a ridiculous amount of people from this game wanting this extension..

skype name is forgotten warrior
its a picture of my son and I playing pool

~thanks for your time, really hope to hear from you soon..
David

**Comment by funkybunny2004** [comment]
yes  please fix. or let us know whats wrong.  its not working for me either.  looks like it ws updated

**Comment by mikecrittenden** [comment]
Sorry about this, but I had to make the decision to not support things specifically for Tribal Wars players. I'd happily accept PRs, but it's a good bit of work to be creating functionality for such a small subset of the extension's users.

**Comment by funkybunny2004** [comment]
It’s working now again.  Not sure what changed. 

Sent from my iPhone
Scott Dembraski
(262)388-9079

**Comment by David050203** [comment]
Understandable ;) I do know after playing TW for the last 10 years that a ton more of us would use this if a couple things were added but maybe enough people already use this that it doesn't matter lol, I love it and it helps me a ton so won't be greedy haha thanks for your time and thanks for the tool;)
