### ISSUE TITLE
Inaccurate action label for new shortkey

### ISSUE THREAD

**Issue by jpalmieri** [mikecrittenden/chrome-shortkeys#36]
Somewhat of an edge case scenario, but I think it's worth an attempt to solve:

![image](https://cloud.githubusercontent.com/assets/4692673/13907529/8014b316-eead-11e5-9037-8cf90e67578b.png)

Steps to reproduce:
1. Add a new shortkey
2. Choose an action from the "Behavior" select list
3. Choose an action from the "Behavior" select list again

Observe that the label of the new shortkey doesn't match the selected option. Also, custom settings for certain actions are now not linked to the correct option in the select list. For example, choosing "Run Javascript" won't display the JS text area, but choosing "Reset Zoom" (the option immediately above it in the list) will display the JS text area. So the index seems to be off by one in this case.

Note that this bug only occurs if the shortkey hasn't yet been saved.

**Comment by mikecrittenden** [comment]
This seems fixed in the latest dev version.
