### ISSUE TITLE
Global shortcuts (e.g. any tab)

### ISSUE THREAD

**Issue by iFedaka** [mikecrittenden/chrome-shortkeys#38]
I'm not sure it even possible, but I'd like to have ability to assign shortcuts globally.

My use-case is to be able to switch between tabs using ctrl+down and ctrl+up, in activate settings I chose  All Sites and noticed that shortkeys works perfect on all sites (except chrome.google.com), and it doesn't work in new tab, settings, extensions an so on.

**Comment by mikecrittenden** [comment]
Yeah, unfortunately Chrome doesn't allow extensions to add JS to those system pages (new tab, settings, etc.). So there's nothing I can do there.

**Comment by iFedaka** [comment]
Thank you.
Anyway, those pages aren't so important to have shortcuts here.

**Comment by reagle** [comment]
What about local file:/// Web pages? I've checked that option in the Chrome extension manager but it doesn't seem to work.
