### ISSUE TITLE
Option to disable/enable shortcut temporarily

### ISSUE THREAD

**Issue by Zhouxing-Su** [mikecrittenden/chrome-shortkeys#42]
This would be helpful when there are some potential shortcut key conflict.

**Comment by mikecrittenden** [comment]
One easy way to do this right now would be to change the sites setting for it to "only on these sites" and then leave the text box empty so it won't run anywhere. 

Given that I can't figure out a decent UI for it, it's an uncommon request, and there's that workaround, I'm going to close this for now.
