### ISSUE TITLE
alt+left/right for tab navigation doesnt work when tab is still loading, resp in new tab

### ISSUE THREAD

**Issue by thomasweissgerber** [mikecrittenden/chrome-shortkeys#43]
ive mapped alt+left to "previous tab" and alt+right to the respective "next tab".

now, this works fine except for two cases:

- opening a new empty tab, loading some website and then hitting alt+left, the performed action is "go back"

- same when any old/new tab has not finished loading and i hit alt+left, the performed action is "go back"

in both cases alt+right doesnt do anything at all.

**Comment by adamcaron** [comment]
I experience the same behavior.  

I've mapped `command+right` for 'Next tab' and `command+left` for 'Previous tab`. 

Chrome Version 55.0.2883.95 (64-bit)

**Comment by mikecrittenden** [comment]
This is the same issue as #44.
