### ISSUE TITLE
Add "Search Google for selected text" action

### ISSUE THREAD

**Issue by sambaptista** [mikecrittenden/chrome-shortkeys#45]
Would be nice to be able to bind shortcut on the contextual menu "Search XYZ with google"

**Comment by kthordarson** [comment]
Yes, or a shortcut to jump to the address bar.

**Comment by AlexByte** [comment]
@kthordarson I do not like `ctrl+L`?

**Comment by AlexByte** [comment]
```
function getSelectionText() {
    var text = "";
    if (window.getSelection) {
        text = window.getSelection().toString();
    } else if (document.selection && document.selection.type != "Control") {
        text = document.selection.createRange().text;
    }
    return text;
}

{
var str = encodeURI(getSelectionText());
window.open('https://www.google.com/search?q='+str);
}
```

**Comment by AlexByte** [comment]
@sambaptista  Is it not more convenient to have a built-in implementation?

**Comment by mikecrittenden** [comment]
Yeah, let's reopen, I think this is a good idea.

**Comment by mikecrittenden** [comment]
https://stackoverflow.com/questions/19164474/chrome-extension-get-selected-text

**Comment by AlexByte** [comment]
@mikecrittenden why are you looking for a way to get the selected text into Chrome extension?

**Comment by mikecrittenden** [comment]
So that we can implement the request in this issue?

**Comment by AlexByte** [comment]
It can be implemented if calling [this](https://github.com/mikecrittenden/chrome-shortkeys/issues/45#issuecomment-345858867) js code by shortcut.

**Comment by mikecrittenden** [comment]
I know but I reopened it because it would be nice to have it built in instead of making people write their own JS for it.

**Comment by AlexByte** [comment]
You can call this code in the page context.

**Comment by mikecrittenden** [comment]
Oh yeah I understand, but I'm trying to keep as much as possible in the background JS so that they can be used by chrome.commands.

**Comment by AlexByte** [comment]
OK, i understand

**Comment by mikecrittenden** [comment]
Fix pushed (https://github.com/mikecrittenden/chrome-shortkeys/commit/bb6e772666eb120f22392f95903ed89646fa8997), will be included in the next release.

**Comment by AlexByte** [comment]
in the comments to the extension asked to choose the site to search.

**Comment by mikecrittenden** [comment]
Yeah, it would be nice to have a generic solution to that. Like "enter the URL you want to use and put `%s` where you want the selected text to go. Kind of like how Chrome search engine config works. That what you mean? I'll spin up a ticket for that if so.
