### ISSUE TITLE
Previous/Next Tab not working with Motivation extension

### ISSUE THREAD

**Issue by aleclarson** [mikecrittenden/chrome-shortkeys#49]
I'm using [this extension](https://chrome.google.com/webstore/detail/motivation/ofdgfpchbidcgncgfpdlpclnpaemakoj?hl=en) with chrome-shortkeys (v2.0.17) on Chrome 56.0.2924.87 (64-bit) and my `Previous Tab` shortcut is not working when on the "New Tab" page.

I'm using "command+shift+left" for the `Previous Tab` shortcut.

It works fine when the Motivation extension is disabled.

This may be an issue with Motivation hijacking the keyboard somehow, but not sure.

**Comment by hektr** [comment]
hmmm, I think, this extention captures hotkeys only when you are in a tab with correct http address, started with "http://" or "https://". It can't inject js on a page that does not have correct http address(for example, on empty tab). Is it really work on empty tab, if you disable "Motivation"?

**Comment by aleclarson** [comment]
> It works fine when the Motivation extension is disabled.

Also, I'm not using the Motivation extension anymore, so whatever.

**Comment by mikecrittenden** [comment]
Yeah, unfortunately Chrome doesn't allow us to watch for shortcuts on built-in pages like that.
