### ISSUE TITLE
Is it possible to override sites own shortcuts

### ISSUE THREAD

**Issue by AlexByte** [mikecrittenden/chrome-shortkeys#50]
@mikecrittenden  Some site are already listening to my shortcuts. Can extension override this shortcuts?

**Comment by samcorbin** [comment]
Some sites' shortcut conflict with my shortcut, would be nice to override the site's shortcut.

**Comment by mikecrittenden** [comment]
Unfortunately I don't see any way to make this happen. Chrome extensions aren't allowed to interact with the JS of the sites that the user visits.
