### ISSUE TITLE
Is it possible to add shortcuts such as `ctrl-m` as <enter>  or `ctrl-/` for undo? 

### ISSUE THREAD

**Issue by mpenet** [mikecrittenden/chrome-shortkeys#54]
I am trying to replicate a more emacs'ish feel via your extension. 

Thanks for your work on this by the way, it's quite handy

**Comment by mikecrittenden** [comment]
I don't believe Chrome exposes "Undo" to Extensions (or at least I couldn't find anything about it), and binding something to the enter key may be possible (I'm not sure) but it would likely be a hack and I don't think it would be very commonly used.
