### ISSUE TITLE
Error loading extenstion

### ISSUE THREAD

**Issue by leelingy** [mikecrittenden/chrome-shortkeys#56]
Issue occurred at Step2.3 - clicking "Load unpacked extension" and browse to the app/ directory to install it.

It says "Failed to load extension from: ~\chrome-shortkeys\app
Could not load javascript 'bower_components/mousetrap/mousetrap.min.js' for content script."

How can I install mousetrap.min.js? I tried installing bower mousetrap. None of the packages are mousetrap.min.js

Also. the drop box link at step 3.1 is missing. 

Thanks!

**Comment by mikecrittenden** [comment]
Did you run the `bower install` step? Did that download things to `/bower_components`?
