### ISSUE TITLE
Mouse shortkeys

### ISSUE THREAD

**Issue by rybarova** [mikecrittenden/chrome-shortkeys#59]
Hello is possible to create shortkeys on mouse buttons? Example mouse7 : previous page;  mouse8 : next page; wheelup : javascript; etc

Is that possible?

**Comment by mikecrittenden** [comment]
Not with this extension - you might want to try https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en
