### ISSUE TITLE
Add per-shortcut option to also activate when form fields are focused

### ISSUE THREAD

**Issue by claudyus** [mikecrittenden/chrome-shortkeys#6]
A great improvement could be allow the use of some shortkey also when you are editing a form.

For example I use ctrl+right and ctrl+left to switch to next/previous tab. Those combination are safe and can be catched also on form inputs.
The extensions, should allow the user to enable some shortkeys when he/she belive that it's "form safe".

Thanks for your plugin!

**Comment by fbm-static** [comment]
+1

**Comment by caeldom** [comment]
Will this feature be implemented soon? Shortcuts still don't work when forms are in focus.

**Comment by mikecrittenden** [comment]
This is done in the overhaul branch (which also includes a UI overhaul to the options page). Should go to the webstore within the next couple days.

**Comment by mikecrittenden** [comment]
Here's a screenshot of the new UI, in which the form fields checkbox is visible. https://www.dropbox.com/s/wtstodpdki0x3ov/Screenshot%202015-07-27%2007.48.03.png?dl=0
