### ISSUE TITLE
Add "Load URL in background tab" action

### ISSUE THREAD

**Issue by jcohenadad** [mikecrittenden/chrome-shortkeys#64]
Hi,

I am running mac OSX (10.10.5) with Chrome (61.0.3163.100). I have a simple script where I want to create a new tab in the background. Here is the command:
~~~
chrome.tabs.create({"url": "https://www.google.com", "selected": false});
~~~

When calling this code from the Chrome console, it works, however when including this script inside the Shortkey Extension, it does not work (nothing happens).

Thanks for your help

**Comment by mikecrittenden** [comment]
Yeah sadly Chrome doesn't seem to allow this. Is the issue just that you need to be able to create a background tab?

**Comment by jcohenadad** [comment]
@mikecrittenden yes that's exactly the issue

**Comment by mikecrittenden** [comment]
@jcohenadad I just pushed https://github.com/mikecrittenden/chrome-shortkeys/commit/d12f1f92ad0e34305b738eb5cce320c0ef838815 which should fix this (it adds a new "Open bookmark in new background tab" action), provided that you're OK making the URL into a bookmark for this purpose. Does that work for you?

**Comment by jcohenadad** [comment]
@mikecrittenden: thank you, but unfortunately this does not help, because the goal of the script was to get the URL from the google search (not the bookmark), as described here:
https://superuser.com/questions/1234766/how-to-use-keyboard-to-navigate-google-search-results-now-that-instant-search-i

**Comment by jcohenadad** [comment]
for information, i found the solution to my problem here:
https://github.com/infokiller/google-search-navigator

thank you for your support

**Comment by mikecrittenden** [comment]
Ok cool, yeah thinking about it more, this seems like a tough problem to solve. Browsers don't allow you to open new background tabs from in-page JS, and the "Run Javascript" action in Shortkeys runs in-page JS. We'd have to dynamically parse out the things that need to run in the extension's background page (such as chrome.whatever) and send messages to the background page for that stuff, and it'd be gross and most likely buggy.
