### ISSUE TITLE
CMD+⇑ for "Go forward"

### ISSUE THREAD

**Issue by andreasemer** [mikecrittenden/chrome-shortkeys#65]
I wanted to bind the shortcut "CMD+⇑" to the command "Go forward" and have tried the following combinations for the shortcut:

CMD+↑
CMD+⇑
⌘+⇑
⌘+↑
⌘+up
⌘+UP
CMD+UP
CMD+up

Nothing worked for me. Can you please give me a hint how to bind this shortcut? Im using the latest Chrome 62.0.3202.94, with the latest version of the extension with OsX 10.13.1

I have seen issue https://github.com/mikecrittenden/chrome-shortkeys/issues/2 is closed, but its still a issue for me.

**Comment by jpalmieri** [comment]
`command+up` is working for me with `Go Forward` in Chrome on Mac 10.31.1

@andreasemer Have you tried `command+up`?

**Comment by andreasemer** [comment]
Thank you very much, this combination works! Whoho :+1:
