### ISSUE TITLE
Settings cannot save if they exceed the 8KB quota for storage.sync

### ISSUE THREAD

**Issue by ambrt** [mikecrittenden/chrome-shortkeys#67]
If you apply function to key  that will have a lot of code, the extension will break.

The problem is that extension tries to write to sync, when sync has limit of size for each item (if i remember well quota is 8k).

**Comment by mikecrittenden** [comment]
Can I see an example of one that's breaking for you? Just paste the code here (if it's not sensitive/private).

**Comment by mikecrittenden** [comment]
https://stackoverflow.com/a/29732624/183929 has some information. Apparently the max length for individual items is 8k if you use `storage.sync`. We could possibly switch to `storage.local` and rely on #55 (import/export) instead of sync.

**Comment by AlexByte** [comment]
`storage.sync` should be used. Synchronization of settings is convenient, it should not be discarded. If the limit is exceeded, you can create an additional item.

**Comment by mikecrittenden** [comment]
@AlexByte but what about situations where a single shortcut exceeds the limit, such as if there is a JavaScript snippet that is very large. Are you suggesting that we should split that snippet in half, or would you be okay falling back to local storage in that case?

**Comment by AlexByte** [comment]
You can assign an bookmarklet instead of code.

**Comment by AlexByte** [comment]
@mikecrittenden This issue is about exceeding the limit with a single shortcut.

**Comment by mikecrittenden** [comment]
Yeah, I do think that it probably makes a lot of sense to make each shortcut its own storage item instead of sticking them all in the same storage item, but it is still possible for a single shortcut to exceed the limit if the shortcut is to run custom code and the custom code is really long. You're right, they could put that in a bookmarklet, but that's not exactly a great workaround. I think at the very least we should detect that sync fails and fall back to local storage if and when that happens. Thoughts?

**Comment by AlexByte** [comment]
I'm against full switching to local.storage. There you can save only large snippets (>8K ) in order not to exceed the limit of 102,400 bytes. And probably should show in UI that there will be no synchronization.

**Comment by mikecrittenden** [comment]
Ok awesome, so:

1) switch to making each shortcut a separate storage item
2) still default to sync
3) detect when a shortcut is too big to sync and fall back to local in that case, and alert the user that that shortcut is too large to sync

Yeah?

**Comment by AlexByte** [comment]
In my opinion, it's best not to synchronize shortcuts that lead to exceeding the limit in 8,192 QUOTA_BYTES_PER_ITEM

**Comment by mikecrittenden** [comment]
Cool, I'm with you. Thanks for the feedback! I'm on it!

**Comment by AlexByte** [comment]
@mikecrittenden Maybe the author wants another.
Also there is an option to save such shortcuts in local storage and again recommend using the bookmarklet.

**Comment by mikecrittenden** [comment]
The author? You mean me?

**Comment by AlexByte** [comment]
The author of the issue/

**Comment by AlexByte** [comment]
Now json of my settings weighs 7916 kilobytes, so I would not reject the option of splitting json into several items.

**Comment by mikecrittenden** [comment]
Haha nice, you're right on the border. @ambrt feel free to weigh in!

**Comment by AlexByte** [comment]
But in this case, you need to carefully consider supporting the loading of the old storage scheme. You can add an additional item and store the names of additional elements or add a similar field to the original json element.

**Comment by AlexByte** [comment]
Still, you can not save huge shortcutsbecause otherwise the limit of 102,400 QUOTA_BYTES will suffice only for 12 shortcuts the size of 8,192, and in fact there are other extensions.

**Comment by AlexByte** [comment]
@mikecrittenden what's the size of your json with settings?

**Comment by mikecrittenden** [comment]
Oh mine is tiny, like 1KB. I only use a few basic ones.

**Comment by AlexByte** [comment]
I found a library to store objects larger than is allowed by default. Useful for Google Chrome extensions and apps. Also it uses LZW compression, which compresses [3 times](https://jsfiddle.net/ryanoc/fpMM6/).
https://www.npmjs.com/package/chrome-storage-largesync

**Comment by mikecrittenden** [comment]
Wow this looks perfect!

**Comment by AlexByte** [comment]
My other extension, use 339+1560=1899 bytes.

**Comment by mikecrittenden** [comment]
That library looks perfect I mean.

**Comment by mikecrittenden** [comment]
As a quick fix since lots of people have emailed me about this, I merged a fix which successfully falls back to local storage when syncing fails, and alerts the user that everything saved but that it wouldn't sync. 

I did NOT split the data up into multiple items, one per shortcut. That's a bigger lift and I'll have to think about the best way to model that data.

**Comment by ambrt** [comment]
@AlexByte Thank you for discussion and @mikecrittenden  thanks for fix.

The use case for large code is one shortcut for many pages that has similar function.

Like to go to  next page on many different sites i do many times :

```
try {
  //  site specific query
}  catch(err)
{
   console.log(err)
}
try {
    // another site specific query
} catch(err)
{
  console.log(err)
}

etc...
```

This is where i hit the limit of 8k per item.

I might use separate key-shortcut for each site but problem would be that it would take more time and effort then just adding another `try/catch`.<br>
And with one long item user can just copy one block and save it to file for backup since the export function isn't there yet. So thats why i posted this issue.

**Comment by AlexByte** [comment]
@ambrt In the extension, only the first shortcut with the same combination is executed

**Comment by mikecrittenden** [comment]
@AlexByte FWIW that was actually fixed in #73 and went out yesterday.

**Comment by AlexByte** [comment]
@mikecrittenden good

**Comment by AlexByte** [comment]
@ambrt You can backup using [Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb)

**Comment by ambrt** [comment]
@AlexByte I did that. Thanks.

**Comment by AlexByte** [comment]
@crittermike  Why don't you use library [chrome-storage-largeSync](https://github.com/dtuit/chrome-storage-largeSync#largesync---chrome-storage-largesync), which is used, for example, by the extension [User JavaScript and CSS](https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld)? "largeSync exposes the same api schema as [chrome.storage](https://developer.chrome.com/apps/storage#type-StorageArea)"



> Wow this looks perfect!
> […](#)
> On Nov 18, 2017 17:56, "AlexByte" ***@***.***> wrote: I found a library to store objects larger than is allowed by default. Useful for Google Chrome extensions and apps.

```javascript
[Methods](https://github.com/dtuit/chrome-storage-largeSync#methods)
//get: Gets one or more items from storage.
largeSync.get(string or array of string or object keys, function callback);

//getBytesInUse: Gets the amount of space (in bytes) being used by one or more items.
largeSync.getBytesInUse(string or array of string keys, function callback);

//set : Sets multiple items.
largeSync.set(object items, function callback);

//remove: Removes one or more items from storage.
largeSync.remove(string or array of string keys, function callback);

//clear: Removes all items from storage.
largeSync.clear(function callback);
```
