### ISSUE TITLE
No longer works in form fields

### ISSUE THREAD

**Issue by swestAncestry** [mikecrittenden/chrome-shortkeys#69]
All scripts that we've had running while the cursor is in form fields have stop working. When we click out the commands work as expected. Unfortunately there are some items that must be initiated from within a form.

**Comment by mikecrittenden** [comment]
Shoot! I'll investigate tonight. Sorry about that!

**Comment by swestAncestry** [comment]
Thank you for the prompt response! Happy bug hunting. :)

On Nov 17, 2017, at 2:57 PM, Mike Crittenden <notifications@github.com<mailto:notifications@github.com>> wrote:

Shoot! I'll investigate tonight. Sorry about that!

**Comment by marylou256** [comment]
Hello. I'm having the same problem. I'm in the middle of work (transcriber) and I need it badly. Help!

**Comment by mikecrittenden** [comment]
I just pushed 2.0.19 to the webstore which should fix this. You can visit chrome://extensions and click "Developer mode" then "Update extensions now" until the version listed for Shortkeys is 2.0.19 if you're in a rush. It might take a bit before the webstore distributes it to you.

Feel free to reopen if you have 2.0.19 and this still isn't working!

**Comment by mikecrittenden** [comment]
Hey @ccampbell does this seem like the correct fix after upgrading Mousetrap? https://github.com/mikecrittenden/chrome-shortkeys/commit/d90fb3eb11dd26f95db6354ddd4560e95a65adc7

**Comment by marylou256** [comment]
Thanks, @mikecrittenden for responding so quickly. I'll look into that.

**Comment by ccampbell** [comment]
Yeah. Assuming you haven’t updated in a while. [Version 1.5](https://github.com/ccampbell/mousetrap/releases/tag/1.5.0) changed that. Should be good though!
