### ISSUE TITLE
Please use "Press" instead of "Hit" in documentation

### ISSUE THREAD

**Issue by DoctorBits** [mikecrittenden/chrome-shortkeys#70]
Minor documentation issue.

This is as old as interactive computing. People used to abuse keyboards (thinking they had to stroke the key very hard if it says "Hit". "Hit" also does not work with tablets or other mobiles.

The attached low-resolution image is from the early 1980's (it was hand drawn and passed around as photocopies - this scan was from a multi-generational photocopy). A lot of old programs used "Hit any key to continue." Support personnel got tired of people calling to ask where the "Any" key was and they got tired of replacing keyboards.
 
![hitanykeytocontinue](https://user-images.githubusercontent.com/33768281/32974610-54d8bb3a-cbb4-11e7-81d2-d62170a698a0.jpg)
Source: http://image.wikifoundry.com/image/1/WMJjHdxX6tssIgqQBUE5pA211141

**Comment by mikecrittenden** [comment]
This is a fascinating issue. Sure, I'll fix it up.

**Comment by mikecrittenden** [comment]
Should be fixed now:

- https://github.com/mikecrittenden/chrome-shortkeys/wiki/How-To-Use-Shortkeys/_compare/8dedbd3c73681f4ce82f5c0f9bffe0f8c5c9a507...19a4a6e24088ce2664a7fda56a009608cb7c2753
- https://github.com/mikecrittenden/chrome-shortkeys/commit/f68fdc8aff01e932a57361f042d853c49b3b36a9
