### ISSUE TITLE
If you have multiple shortcuts that use the same combination on different websites, only the last one works

### ISSUE THREAD

**Issue by sirius16** [mikecrittenden/chrome-shortkeys#73]
Ever since the 2.0.19 (11/17) update, some of my shortcuts don't work, but when I recreate them to be identical, then they work

**Comment by mikecrittenden** [comment]
Can you post an example of one where this happened? Also, does #71 seem like the same issue possibly?

**Comment by sirius16** [comment]
How do you want me to post this?

**Comment by mikecrittenden** [comment]
Oh I just mean something like:

```
shortcut: ctrl+a
action: next tab
use in form fields: unchecked
sites: all sites
```

**Comment by sirius16** [comment]
Shortcut: ; 0
Action: Run Javascript
Use in form fields: unchecked
Sites: *mail.google.com*

Shortcut: space
Action: Run Javascript
Use in form fields: unchecked
Sites: *://kissanime.ru/BookmarkList

**Comment by sirius16** [comment]
Also, it doesn't matter what I change the action to, it just doesn't work. However, change the shortcut key seems to make it work

**Comment by mikecrittenden** [comment]
Ok 2 more questions:

1) did it only happen on shortcuts that are only enabled for specific sites? And the ones that are enabled globally did not break?
2) does it work when you change it back to the original shortcut?

**Comment by sirius16** [comment]
I figured out the problem, if I have multiple shortcuts that use the same key, but for different sites, then only the last one of said shortcuts will work

**Comment by sirius16** [comment]
For example, if I have 3 shortcuts that use space (all for different websites), only the last one will work

**Comment by mikecrittenden** [comment]
Oh! Excellent find! That makes total sense why that would be the case. I'll fix it.

**Comment by sirius16** [comment]
👌👌👌

**Comment by mikecrittenden** [comment]
https://github.com/mikecrittenden/chrome-shortkeys/pull/78 should fix this. It'll be included in the next release.

**Comment by sirius16** [comment]
Thank you
