### ISSUE TITLE
Consider adding a browser action button as a shortcut to settings 

### ISSUE THREAD

**Issue by mikecrittenden** [mikecrittenden/chrome-shortkeys#74]

**Comment by mikecrittenden** [comment]
Looks like this already happens OOTB.

**Comment by AlexByte** [comment]
This is not true.

**Comment by AlexByte** [comment]
This is not true.

**Comment by mikecrittenden** [comment]
@AlexByte I meant that this exists just because the extension is installed:

![2017-11-20 at 6 41 pm](https://user-images.githubusercontent.com/32261/33047176-6f87ffd4-ce22-11e7-983c-4237377b8135.png)

That's all I was thinking of adding. Did you have something else in mind here?

**Comment by AlexByte** [comment]
Open settings by clicking the button.
