### ISSUE TITLE
Add a "Insert custom text at cursor" action

### ISSUE THREAD

**Issue by wesort** [mikecrittenden/chrome-shortkeys#85]
I'd like to map a keyboard shortcut for `alt+shift+-` (hyphen) to insert em dash character (`\u2014` or `&mdash;`). This is a common character to use but on Chrome OS it is laborious. One has to use `ctrl+shift+u` in an input field and then type in the unicode entry for the special character you want. An em dash is `2014`.

I presume this would utilise the Run Javascript option, but I'm not a programmer. Could you add some example documentation for how to do this?

**Comment by mikecrittenden** [comment]
I renamed this to be more general - lots of people have asked for a way to just insert some arbitrary text with a command and I think that would be a really useful thing to support.

I tried to find a good way to do this in regular old JS but it didn't seem to be easy - there are some solutions on StackOverflow but none of them seem to work for me.

**Comment by mikecrittenden** [comment]
After thinking about this, I think we're better off pointing people to https://chrome.google.com/webstore/detail/auto-text-expander-for-go/iibninhmiggehlcdolcilmhacighjamp?hl=en instead, since that already does things like this very well.

**Comment by jeromelbl** [comment]
Late to the game here, but I was looking for the same thing. You can achieve it in ShortKeys using the Run Javascript behavior with the following code:

document.execCommand("insertText", false, "some text here");
