### ISSUE TITLE
`alt+shift+]` doesn't work for "Next tab"

### ISSUE THREAD

**Issue by barmstrong** [mikecrittenden/chrome-shortkeys#88]
I'm trying to use `ctrl+shift+]` for "Next tab" and `ctrl+shift+[` for "Previous tab" on a chromebook (mimicking this keyboard shortcut that is on macs).

For some reason it doesn't work. It does work if I try `ctrl-shift-O` and `ctrl-shift-P`.

Any ideas? Thx for the awesome extension!

**Comment by mikecrittenden** [comment]
I'm not sure, both `alt+shift+[` and `ctrl+shift+[` worked for me (and save for the `]` versions of those as well) but I'm on a Mac and I don't have any way to test on a Chromebook unfortunately.

Are you adding these shortcuts from the Shortkeys options page, which looks like this: 

![2017-11-27 at 9 48 am](https://user-images.githubusercontent.com/32261/33272452-2cce5d92-d358-11e7-8d66-0a1283baa521.png)

Or are you adding them from the Chrome keyboard shortcut options, which looks like this:

![chrome](https://user-images.githubusercontent.com/32261/33272475-3f356d2c-d358-11e7-9cfd-0d11b1fdc4ff.png)
