### ISSUE TITLE
request feature - toggle sendkey mode

### ISSUE THREAD

**Issue by ghost** [mikecrittenden/chrome-shortkeys#9]
Specifically I'm interested in being able to simulate key presses on text components where default shortcut keys for the component conflict with browser shortcuts.

It would be very useful if the plugin could provide a check box or other means of turning on/off a "sendkey mode" such that any focused component would then receive all simulated key combinations from the user.

I've not found a plugin which offers this kind of feature, but it has been requested on stackoverflow and I saw something about key simulation in the plugin api.

Is this possible?

**Comment by mikecrittenden** [comment]
I'm going to close this because 1) it's only been requested this once in the 3-4 years that the extension has existed and 2) it doesn't really seem possible, or at least not at all trivial, after spending a few minutes digging through Chrome's extension API.
