### ISSUE TITLE
Allow the usage of Shortkeys with file:///

### ISSUE THREAD

**Issue by owensgithub** [mikecrittenden/chrome-shortkeys#90]
I assumed this was a limitation of the Firefox's API, but there's an add-on with the ability to close other tabs, such as internal pages. Here's the add-on: https://addons.mozilla.org/en-GB/firefox/addon/close-other-tabs-shortcuts/ 

It would be great to see this addition, as there's so many usages for this.

**Comment by mikecrittenden** [comment]
Just pushed a fix, but note that it won't be available in the Firefox version of the extension until @pmalecka merges it to https://github.com/pmalecka/chrome-shortkeys and rolls a new release.

**Comment by owensgithub** [comment]
Thanks for the speedy fix Mike.

**Comment by mikecrittenden** [comment]
No worries, thanks for the request!
