### ISSUE TITLE
F2, F3, F4 do not work for previous/next/close tabs

### ISSUE THREAD

**Issue by smnlng** [mikecrittenden/chrome-shortkeys#92]
This used to work fine, but recently F3 brings up Find in Page instead of "Next Tab". Mapping via Chrome Extensions doesn't work since standard "F" keys don't seem to be mappable. Any suggestions?

**Comment by mikecrittenden** [comment]
Are you on Windows by any chance? F1/2/3/4/5 all seem to be working fine for me on a Mac. It's possible that the Windows version just recently made F3 be the shortcut for Find in Page I suppose, which could theoretically cause this.

**Comment by smnlng** [comment]
Yes, I'm on Windows. 
F1 = help, 
F2 = nothing, 
F3 = find in page, 
F4 = nothing, 
F5 = refresh.

**Comment by mikecrittenden** [comment]
Gotcha. I'm not really sure of anything we can do here. It seems that something recently changed in Windows or Chrome that started hogging control of those buttons.

Just to double check, are you using `f3` or `F3`? If using uppercase, try it with lowercase, and vise versa.

**Comment by mikecrittenden** [comment]
Going to close this one for now since I don't believe there's anything I can do here, but please reopen if you disagree.

**Comment by smnlng** [comment]
lowercase f2/f3/f4 did the trick. Thanks!
