### ISSUE TITLE
I need disable hot key "ctrl + mouse scroll" (zoom) in Chrome. Is it possible?

### ISSUE THREAD

**Issue by zamboga** [mikecrittenden/chrome-shortkeys#95]
I need disable hot key "ctrl + mouse scroll" (zoom) in Chrome.
Can do I this via you extension? Is it possible?

**Comment by mikecrittenden** [comment]
Unfortunately not - Shortkeys is keyboard-only and doesn't know anything about mouse buttons/gestures.

If you're in Firefox this is disable-able here: https://support.mozilla.org/en-US/questions/1113500

Assuming you're in Chrome, though, it looks like the best you can do is to download AutoHotKey and do it from there. The script to use is here: https://productforums.google.com/d/msg/chrome/-rtDLZmN9bk/_Dbsloyup40J

**Comment by zamboga** [comment]
Thank you!
I Will try it.
