### ISSUE TITLE
Pop up options? 

### ISSUE THREAD

**Issue by Lotsofjoy** [mikecrittenden/chrome-shortkeys#99]
So, my options JUST turned into a pop up on the extensions page instead of their own tab. I actually mess with a few of them constantly to make them match the project that I'm working on so I have a tool bar bookmark that lets me just click on it and get right to the options window. So the pop up thing makes it really cumbersome to work with. 

Is there a way to bypass the pop up and put it in it's own window/tab?

**Comment by Lotsofjoy** [comment]
Added: 
When my script has long strings of data, the pop up doesn't wrap. it just extends the pop up and creates this crazy long string scrolling to the right.

**Comment by Lotsofjoy** [comment]
AND.... I just got this message at the top of the pop up. I've never seen that before. 

"Your settings were saved, but they were too large to be synced to any other Chrome installations you have due to Chrome's 8KB limitation on the storage sync API. Everything will still work, but if you are logged into Chrome on any other computers, the settings won't sync there."

**Comment by mikecrittenden** [comment]
Unfortunately Chrome is deprecating the "separate page options UI" thing. See https://developer.chrome.com/extensions/optionsV2#open_in_tab - there's not really anything I can do there. 

Can you add line breaks in your script so it doesn't get super wide like that? And just make the bookmark point to chrome://extensions/?options=logpjaacgmcbpdkdchjiaagddngobkck?

**Comment by mikecrittenden** [comment]
@Lotsofjoy oh and as for that message about them being too large, that's due to #67 - in the past, settings would fail to save if they were too big, and now there's a fallback for that so that it doesn't break anything.

**Comment by Lotsofjoy** [comment]
Well BOO on Google for that one then. 

Yeah, I can bookmark the extensions page, but still so many more scolls+steps to get where I need to be. it was SO convenient to just be able to get right to the specific options for shortkeys!  I'll deal with it though, first world problems, right? :D 

THANKS for being awesome!

**Comment by mikecrittenden** [comment]
No worries, sorry about that. It's been throwing a lot of people for a loop.
